// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV20LIq2AFSGdS_UcOAtNGsVvTZn8gWMQ',
    appId: '1:598410561447:web:52aca8df35ad5a2f779882',
    messagingSenderId: '598410561447',
    projectId: 'jansampark3-5a235',
    authDomain: 'jansampark3-5a235.firebaseapp.com',
    storageBucket: 'jansampark3-5a235.appspot.com',
    measurementId: 'G-ZXLX1VL9E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_tqEHYJD0eUNR7ZBUkbGvcUQXohBJwu8',
    appId: '1:598410561447:android:fecafa0403f8be34779882',
    messagingSenderId: '598410561447',
    projectId: 'jansampark3-5a235',
    storageBucket: 'jansampark3-5a235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgUCFCoXMJ_TArKMRJfnh_stYzk80WI_U',
    appId: '1:598410561447:ios:aa0f96dcc77bd856779882',
    messagingSenderId: '598410561447',
    projectId: 'jansampark3-5a235',
    storageBucket: 'jansampark3-5a235.appspot.com',
    iosBundleId: 'com.example.jan',
  );
}
